[dependencies]
actix-web = "4"
actix-multipart = "0.6"
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
reqwest = { version = "0.11", features = ["multipart", "stream"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tempfile = "3"